### PR TITLE
No more unnecessary string copies

### PR DESCRIPTION
**Pull request by 2xsaiko**
Basically just replaces a bunch of `Into<String>` with `AsRef<str>`.

### CODE REVIEW

**Comment by Morganamilo** [comment]
[CString::new](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.new) requires an `Into<Vec<u8>>`. `&str` implements this making a vector and cloning itself into it.

This means that it would clone every time.

Taking `String` means the memory could be moved instead of copied.

Remember that c strings are null terminated, so anything we pass from rust needs to have that null byte pushed to it.

However, If a String has no extra capacity, pushing to the string may cause it to realloc, or even worse, reallocate, so I guss neither are idea. But I feel this way at least adds more control because it doesn't guarantee a copy.

Hell if you really wanted you could allocate the string with capacity of length + 1 to give yourself room for the byte. But that's probably a micro optimisation that's not needed.

Anyway, thanks, I get this is what you would typically do in rust, but for c strings it's a little different.

**Comment by 2xsaiko** [comment]
Oh, whoops. I even looked at the constructor for CString and must have missed that it takes `Into<Vec<u8>>` and not `&[u8]` or anything like that. Well that's annoying.

I guess I can still PR the fixes for some of the stuff though that I put in here, like [this](https://github.com/Morganamilo/alpm.rs/pull/5/files#diff-64079857da17427e4b306f9739f60d3dR68).

**Comment by Morganamilo** [comment]
I never read the PR because I assumed it was just the Into/AsRef change. If you have other things you wanna change, make a new PR and I'll happily look at it.

**Comment by 2xsaiko** [comment]
Yup, will do. I guess I'll close this for now, then.

**Pull request closed without merging**
