### PR TITLE
Github CI

### PR DESCRIPTION
**Pull request by fosskers**
This PR adds a Github Actions definition to build and test the three libraries in this repo. The actual tests are ran in an Arch Linux docker image with Rust installed, ensuring that `libalpm` exists in the testing environment.

### CODE REVIEW

**Comment by fosskers** [comment]
I'm not sure why this action definition didn't kick in. You may need to activate something in Settings/Actions.

**Comment by Morganamilo** [comment]
I built on this PR and made my own CI here: https://github.com/Morganamilo/alpm.rs/commit/7708da02fb0ad3718a33a27576dd50f18fcbdc81. I'll probably merge this instead, not to ignore the work you did.

Basically it tests alpm against pacman-git as well as git.

Also no `-Sy` cause that;s a partial upgrade ;)

**Comment by fosskers** [comment]
I have that `-y` in there to insure that the most recent Rust is pulled.

**Comment by Morganamilo** [comment]
It is to avoid partial upgrades. Anyway are you happy with the other actions file. I've not touched them before so don't really know the best way to do things.

**Comment by fosskers** [comment]
I made some comments on the commit, but otherwise it looks good!

**Comment by fosskers** [comment]
Alright, looks good for now. It looks like your commits were picked up and ran by Github CI, so at least the definitions are right. 

Oh, and you might want to use caching? This PR demonstrates it, it should work as-is.

**Comment by Morganamilo** [comment]
I thought it wasn't needed because alpm has very minimal dependencies. Enabling the generate feature does add to that but I still feel caching is not needed much.

**Comment by fosskers** [comment]
Gotcha. Yeah even without it, the deps build pretty quickly. All in all each CI run should take less than a minute.

**Comment by Morganamilo** [comment]
Merged the other file then, thanks for the help setting up CI.

**Pull request closed without merging**
