### PR TITLE
Db::servers Lifetime

### PR DESCRIPTION
**Pull request by fosskers**
This is an experiment to determine whether the previous anonymous lifetime is the source of issues I'm having. If it is, then I'll undraft this.

### CODE REVIEW

**Comment by fosskers** [comment]
Hm, it doesn't seem to fix it. 

Do you know why this compiles:
```rust
        let names: Vec<_> = dbs.iter().map(|db| (db.name(), db.name())).collect();
```
but this does not?
```rust
        let inner: HashMap<&'a str, Vec<&'a str>> = dbs
            .iter()
            .map(|db| (db.name(), db.servers().iter().collect()))
            .collect();
```

**Comment by Morganamilo** [comment]
Works for me. What's the full code?

**Comment by fosskers** [comment]
Something along the lines of:
```rust
pub fn new(dbs: AlpmList<'a, Db<'a>>) -> MirrorMap<'a> {
    let inner: HashMap<&'a str, Vec<&'a str>> = dbs
        .iter()
        .map(|db| (db.name(), db.servers().iter().collect()))
        .collect();
// use inner
}
```

**Comment by Morganamilo** [comment]
Where is the lifetime defined in new?

**Comment by fosskers** [comment]
Fuller example:
```rust
impl<'a> MirrorMap<'a> {
    pub fn new(dbs: AlpmList<'a, Db<'a>>) -> MirrorMap<'a> {
        let inner: HashMap<&'a str, Vec<&'a str>> = dbs
            .iter()
            .map(|db| (db.name(), db.servers().iter().collect()))
            .collect();

        MirrorMap { inner }
    }
}
```
Even if I slap a `&` on the `AlpmList` it doesn't like it.

**Comment by fosskers** [comment]
This is complaining too:
```rust
        // Show servers
        for p in ps {
            let mirror = p.db().and_then(|db| db.servers().first());
        }
```

**Comment by fosskers** [comment]
And now it hates me again :laughing: 
```rust
        for p in ps {
            let mirror = p.db().as_ref().and_then(|db| db.servers().first());
            println!("{:?}", mirror);
        }
```
citing
```
    |
198 |             let mirror = p.db().as_ref().and_then(|db| db.servers().first());
    |                          ^^^^^^                                             - temporary value is freed at the end of this statement
    |                          |
    |                          creates a temporary which is freed while still in use
199 |             println!("{:?}", mirror);
    |                              ------ borrow later used here
    |
    = note: consider using a `let` binding to create a longer lived value
```

**Comment by Morganamilo** [comment]
> Fuller example:
> 
> ```rust
> impl<'a> MirrorMap<'a> {
>     pub fn new(dbs: AlpmList<'a, Db<'a>>) -> MirrorMap<'a> {
>         let inner: HashMap<&'a str, Vec<&'a str>> = dbs
>             .iter()
>             .map(|db| (db.name(), db.servers().iter().collect()))
>             .collect();
> 
>         MirrorMap { inner }
>     }
> }
> ```
> 
> Even if I slap a `&` on the `AlpmList` it doesn't like it.

Works for me still. Are you sure you're depending alpm with this included and not just the standard one from crates.io?

**Comment by fosskers** [comment]
Ahh it was me not accounting for the 3 places that I'm actually declaring `alpm` as a dependency. I seem to recall somebody warning me about all the subcrates... now who was that... :thinking: 

Okay, with this PR, this now works, with or without the `&` on the `AlpmList` arg.

**Comment by fosskers** [comment]
Shall I add a CHANGELOG?

**Comment by Morganamilo** [comment]
See https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html That will propagate to deps of deps.

Probably not. This was a bug so there's no change of functionality, it should have always been this way. And as this is a strict wrapper over alpm I don't see us ever making any changes that are not just changes from alpm ittself.

**Comment by fosskers** [comment]
In that case this should be good to go.

**Comment by fosskers** [comment]
Cool, specifying this at the workspace root does the trick:
```toml
[patch.crates-io]
alpm = { git = "https://github.com/fosskers/alpm.rs", rev = "9072a3b77a2f1d681bc2d9891c65766484cf7b9e" }
```

**Pull request merged**
